package ru.balmukanov.codewars.algorithms.morse;

public class MorseCode {
    public static String get(String code) throws Exception {
        switch (code) {
            case ".-":
                return "A";
            case "-...":
                return "B";
            case ".--":
                return "W";
            case "--.":
                return "G";
            case "-..":
                return "D";
            case ".":
                return "E";
            case "...-":
                return "V";
            case "--..":
                return "Z";
            case "..":
                return "I";
            case ".---":
                return "J";
            case "-.-":
                return "K";
            case ".-..":
                return "L";
            case "--":
                return "M";
            case "-.":
                return "N";
            case "---":
                return "O";
            case ".--.":
                return "P";
            case ".-.":
                return "R";
            case "...":
                return "S";
            case "-":
                return "T";
            case "..-":
                return "U";
            case "..-.":
                return "F";
            case "....":
                return "H";
            case "-.-.":
                return "C";
            case "---.":
                return "Ö";
            case "----":
                return "CH";
            case "--.-":
                return "Q";
            case "--.--":
                return "Ñ";
            case "-.--":
                return "Y";
            case "-..-":
                return "X";
            case "..-..":
                return "É";
            case "..--":
                return "Ü";
            case ".-.-":
                return "Ä";
            case ".----":
                return "1";
            case "..---":
                return "2";
            case "...--":
                return "3";
            case "....-":
                return "4";
            case ".....":
                return "5";
            case "-....":
                return "6";
            case "--...":
                return "7";
            case "---..":
                return "8";
            case "----.":
                return "9";
            case "-----":
                return "0";
            case "......":
                return ".";
            case ".-.-.-":
                return ",";
            case "---...":
                return ":";
            case "-.-.-.":
                return ";";
            case "-.--.-":
                return "(";
            case ".----.":
                return "`";
            case ".-..-.":
                return "\"";
            case "-....-":
                return "-";
            case "-..-.":
                return "/";
            case "..--.-":
                return "_";
            case "..--..":
                return "?";
            case "--..--":
                return "!";
            case ".-.-.":
                return "+";
            case ".--.-.":
                return "@";
        }

        throw new Exception("Not found code " + code);
    }
}
